apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ckan-storage-pvc
  namespace: vusta-idist-dev
spec:
  accessModes:
    - ReadWriteOnce # Changed to RWO for vSphere CSI
  resources:
    requests:
      storage: 20Gi
  storageClassName: gold-storage-service # vSphere CSI storage class

